# Generated by Django 4.2.4 on 2023-08-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handball_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('capacidad', models.IntegerField()),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Arena',
                'verbose_name_plural': 'Arenas',
            },
        ),
        migrations.RenameModel(
            old_name='Clubes',
            new_name='Club',
        ),
        migrations.RenameModel(
            old_name='Ligas',
            new_name='Liga',
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Club', 'verbose_name_plural': 'Clubes'},
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='liga',
            options={'verbose_name': 'Liga', 'verbose_name_plural': 'Ligas'},
        ),
    ]
